### ISSUE TITLE
Dropbox SDK concerns

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress-pro-dropbox#16]
We're using this SDK https://github.com/BenExile/Dropbox , which is no longer maintained.
The official SDK requires the hardware and PHP to be 64bit. 

For now the third party SDK still works, but it might break one day. We can't realistically require users to migrate to a 64bit environment or just break the plugin.

It's not an issue we need to fix right now, just wanted to write down my thoughts.

**Comment by roborourke** [comment]
Closing due to new API class.
