### ISSUE TITLE
chunked uploads fails

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress-pro-dropbox#23]
backups over 150MB use chunked upload but it fails.

let's try using the chunked upload method from the official SDK
https://github.com/dropbox/dropbox-sdk-php/blob/138bfec02f042fa6a4b384c0ae7ebe92ad122bbd/lib/Dropbox/Client.php

**Comment by pdewouters** [comment]
It should be possible to make the chunked upload work over multiple requests, as per documentation
https://blogs.dropbox.com/developers/2012/08/chunked-uploads-beta/

**Comment by pdewouters** [comment]
We could use the same approach as we do for calculating the folder sizes, but spawning backdrop tasks for each chunk.
Could that have a negative impact? we need to make sure to clean up if a job is aborted.

**Comment by roborourke** [comment]
Guess we can close this and circle back - new version uses 8Mb chunks at most and the v2 API sends back a corrected byte offset to start sending data from if it fails to send everything for some reason.
