### ISSUE TITLE
Unable to update Plugin 

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress-pro-dropbox#26]
Have received a "Too Many Redirects" error when trying to update the plugin. Waiting for a few more details but listing as an issue because I did receive confirmation about it impacting another premium plugin already. 

[Also on S3 at least: https://github.com/humanmade/backupwordpress-pro-s3/issues/23]

Impacted Intercom ticket: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1654470599

**Comment by pdewouters** [comment]
Yes, it seems it is caused by the change I made to `sslverify`

**Comment by katmoody** [comment]
Any update on this one @pdewouters?

**Comment by pdewouters** [comment]
https://github.com/humanmade/Human-Made-website/issues/806#issuecomment-194213131
