### ISSUE TITLE
Fatal Error on Activation Attempt

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress-pro-dropbox#27]
Received report on this, initially thought it was tied to other update issues but it looks like it might be a separate issue. This is on trying to activate 2.1.8 Dropbox Pro plugin

Intercom ticket: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1853341170

![screen shot 2016-02-04 at 1 12 56 pm-2](https://cloud.githubusercontent.com/assets/5481211/12852318/5b029ada-cbfc-11e5-8802-9583e3d27e34.png)

**Comment by pdewouters** [comment]
looks like they're missing some files , check they hav ea  valid license and send a copy of the zip.

**Comment by katmoody** [comment]
Hey @pdewouters -  I pulled that file from the website (bwp.hmn.md) after confirming their license yesterday. :(

**Comment by orangepineapple** [comment]
Hi @katmoody, I ran across this as well when attempting to install the plugin using the Git repository. Looks like you have to run composer in the plugin directory before activating it in WordPress.

When accessing your site via SSH, run the following commands from the wp-content folder:

`git clone https://github.com/humanmade/backupwordpress-pro-dropbox.git
cd backupwordpress-pro-dropbox
composer install`

This will populate the vendor folder that's ignored in the repository.

**Comment by pdewouters** [comment]
ah yes, good catch. I see the folder is named `backupwordpress-to-dropbox-master` so likely installed from the Github repo.
So what @orangepineapple says. 
Also, note that we can't provide support to these users without a valid license key.
