### ISSUE TITLE
Multiple errors impacting updates of plugin

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress-pro-dropbox#28]
Users report getting error messages regarding Dropbox extension. When they try to update the extension, the update isn't working. And they are getting error messages about licenses being expired even though they have months left on their purchase support. 

Tickets Impacted (will add to as needed):
- https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1926033153
- (possibly?) https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1777681901 - the authentication isn't always clearing, but is they are getting error messages about their licenses being expired even though they have months left on their licenses (see images) 

![screen 20shot 202016-02-16 20at 2011 24 43 20am](https://cloud.githubusercontent.com/assets/5481211/13086780/b0b3f3de-d4b2-11e5-86a5-a9c4b72e5c3c.png)

**Comment by katmoody** [comment]
@pdewouters - is this related to #26 as well?

**Comment by pdewouters** [comment]
@katmoody the above screenshot of the error message looks like they are on a very old version? if it is, try deleting it and uploading a fresh copy of the latest version

**Comment by katmoody** [comment]
I've left a message with one user who was most definitely using a much older version of the plugin, but the other linked user is still having multiple issues working with the plugins, including an intermittent Handshake error. I've been continuing to work with them through Intercom, though, so you can catch up there if wanted.

**Comment by pdewouters** [comment]
plugin on the test site is not showing an update despite license being active and the site being registered
<img width="201" alt="screenshot 2016-03-01 18 58 01" src="https://cloud.githubusercontent.com/assets/30460/13438128/8cc3fe00-dfdf-11e5-9d82-937ba908549c.png">

**Comment by pdewouters** [comment]
if I manually change the version number, it prompts to update to `2.1.9` which is the last version for the old dropbox extension post that is in the trash.
<img width="352" alt="screenshot 2016-03-01 21 44 07" src="https://cloud.githubusercontent.com/assets/30460/13443005/df3f6db0-dff6-11e5-949d-e20015bb023a.png">

if updates are somehow linked to the Download post ID, that might be the issue

**Comment by pdewouters** [comment]
handled in https://github.com/humanmade/Human-Made-website/issues/806
