### ISSUE TITLE
Fatal Error: Call to Member Function

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress-pro-dropbox#33]
We're working on multiple issues on this site. BUT when she clicks to "authenticate" the Dropbox plugin she gets this fatal error: 

```Fatal error: Call to a member function error() on a non-object in /home/username/public_html/wp-content/plugins/backupwordpress-pro-dropbox/inc/DropboxBackUpService.php on line 381```

This apparently doesn't come up every time she tries to authenticate on every site, but often enough that she isn't able to get consistent use of the plugin. She originally had issues getting her license key to validate but we have that part of the equation taken care of.

**Comment by pdewouters** [comment]
fixed
