### ISSUE TITLE
Dropbox API v1 Fully Deprecated, causing ext. Failures

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress-pro-dropbox#39]
The SDK used for this uses the Dropbox API v1, which was fully deprecated as of Sept. 28. This is causing authentication failures for users and needs to be addressed ASAP. 

In reading some of the Dropbox documentation, I found this upgrader which will convert v1 OAuth to the new v2 OAuth -- http://dropbox.github.io/dropbox-sdk-php/api-docs/v1.1.x/class-Dropbox.OAuth1Upgrader.html 

Though if we update completely, we might need a full update for the plugin, so requiring re-authentication might be acceptable under those conditions. I'm thinking more of the developers who use the extension on dozens or even hundreds of different sites. :( 

In the [community section](https://www.dropbox.com/developers/documentation/communitysdks), there are two compliant PHP SDKs, both of which are hosted here on GitHub: 
1. https://github.com/kunalvarma05/dropbox-php-sdk (Min PHP v 5.6.4 & mbstring extension)
2. https://github.com/Alorel/dropbox-v2-php (no longer maintained but worth a look? looks like it's only tested against 5.6 and 5.7 - I don't see a quick minimum version listed)

I'm also wondering if there is a use-case to instead use the JavaScript SDK?

@roborourke and @pdewouters (since you're familiar with the currently used SDK)

**Comment by pdewouters** [comment]
that upgrader is not what you think, we were already using oauth2.
The official SDK has a note saying not to use it https://github.com/dropbox/dropbox-sdk-php
So our other options would be to do it directly with WP HTTP API `wp_remote_post`... or use one of those SDKs which are not maintained by dropbox

**Comment by katmoody** [comment]
@pdewouters I'm thinking our best forward-compatible option is to use the WP HTTP API, would you agree? We have several customers who have already reached out and need progress info on this so I'd like to try and put together a plan and then a timeline if possible. 

I'm thinking we might be able to squeeze in some time for testing next week? @roborourke and/or @willmot - this is fairly critical as it is stopping folks from being able to use the extension. 😦

**Comment by pdewouters** [comment]
not sure there will be time at the retreat as the schedule is pretty tight, but happy to look into it -

**Comment by katmoody** [comment]
I've been investigating this further and because it is impacting current users right now, I think we need at least an interim fix ASAP, even if we want to come back to do something better with it. As a result, I've been looking at the one maintained SDK I linked above - https://github.com/kunalvarma05/dropbox-php-sdk

My concern is that the minimum PHP version for that library is 5.6.4 - which will require users to do one more step in order to get it working again. The good news is that this SDK seems to have also tackled options to fix the depreciation of mcrypt with PHP v 7.1

I'd love some feedback so I can beg for developer help with this @willmot or @pdewouters ?? Or?

**Comment by roborourke** [comment]
New custom API handler has been reviewed and merged in #41 so I think we're ready for a new release pending some feedback from a few test customers /cc @katmoody

**Comment by katmoody** [comment]
Hey @roborourke - I've heard back from several users who have had success - think we can go ahead and set up this release?

**Comment by katmoody** [comment]
The 2.3.0 version you've sent me for the beta testing - if that is the correct one then I can start the process once you agree it's a go :grin:

**Comment by roborourke** [comment]
Hey @katmoody - awesome! Yep go ahead and release the 2.3.0 one - I bumped
the version number so it should pick up.

**Comment by katmoody** [comment]
Okay - I updated and sent out notices for the new release and am in the process of checking in with users having any further trouble. I'm closing this out as addressed and done :grin:
